import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

export function registerCodeTemplateGenerator(server: McpServer) {
  server.tool(
    "code_template_generator",
    "根据页面名称和架构模式生成 iOS 代码模板",
    {
      name: z.string().describe("页面或模块名称，如 UserList、Login、OrderDetail"),
      pattern: z.enum(["mvvm", "mvc", "clean"]).describe("架构模式"),
    },
    async ({ name, pattern }) => {
      const templates: Record<string, (n: string) => string> = {
        mvvm: (n) => [
          `// MARK: - Model`,
          `struct ${n}Model {`,
          `    let id: String`,
          `    let title: String`,
          `}`,
          ``,
          `// MARK: - ViewModel`,
          `@MainActor`,
          `class ${n}ViewModel: ObservableObject {`,
          `    @Published var items: [${n}Model] = []`,
          `    @Published var isLoading = false`,
          `    @Published var errorMessage: String?`,
          ``,
          `    func fetchData() async {`,
          `        isLoading = true`,
          `        defer { isLoading = false }`,
          `        do {`,
          `            // TODO: 调用 API`,
          `            // items = try await APIService.fetch${n}()`,
          `        } catch {`,
          `            errorMessage = error.localizedDescription`,
          `        }`,
          `    }`,
          `}`,
          ``,
          `// MARK: - View`,
          `struct ${n}View: View {`,
          `    @StateObject private var viewModel = ${n}ViewModel()`,
          ``,
          `    var body: some View {`,
          `        Group {`,
          `            if viewModel.isLoading {`,
          `                ProgressView()`,
          `            } else {`,
          `                List(viewModel.items, id: \.id) { item in`,
          `                    Text(item.title)`,
          `                }`,
          `            }`,
          `        }`,
          `        .navigationTitle("${n}")`,
          `        .task {`,
          `            await viewModel.fetchData()`,
          `        }`,
          `        .alert("错误", isPresented: .constant(viewModel.errorMessage != nil)) {`,
          `            Button("确认") { viewModel.errorMessage = nil }`,
          `        } message: {`,
          `            Text(viewModel.errorMessage ?? "")`,
          `        }`,
          `    }`,
          `}`,
        ].join("\n"),

        mvc: (n) => [
          `// MARK: - Model`,
          `struct ${n}Model {`,
          `    let id: String`,
          `    let title: String`,
          `}`,
          ``,
          `// MARK: - ViewController`,
          `class ${n}ViewController: UIViewController {`,
          ``,
          `    private var items: [${n}Model] = []`,
          ``,
          `    private lazy var tableView: UITableView = {`,
          `        let tv = UITableView()`,
          `        tv.dataSource = self`,
          `        tv.delegate = this`,
          `        tv.register(UITableViewCell.self, forCellReuseIdentifier: "cell")`,
          `        return tv`,
          `    }()`,
          ``,
          `    override func viewDidLoad() {`,
          `        super.viewDidLoad()`,
          `        title = "${n}"`,
          `        setupUI()`,
          `        fetchData()`,
          `    }`,
          ``,
          `    private func setupUI() {`,
          `        view.addSubview(tableView)`,
          `        tableView.frame = view.bounds`,
          `    }`,
          ``,
          `    private func fetchData() {`,
          `        // TODO: 调用 API`,
          `        // items = APIService.fetch${n}()`,
          `        tableView.reloadData()`,
          `    }`,
          `}`,
          ``,
          `// MARK: - UITableViewDataSource`,
          `extension ${n}ViewController: UITableViewDataSource {`,
          `    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {`,
          `        items.count`,
          `    }`,
          ``,
          `    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {`,
          `        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)`,
          `        cell.textLabel?.text = items[indexPath.row].title`,
          `        return cell`,
          `    }`,
          `}`,
          ``,
          `// MARK: - UITableViewDelegate`,
          `extension ${n}ViewController: UITableViewDelegate {`,
          `    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {`,
          `        tableView.deselectRow(at: indexPath, animated: true)`,
          `        // TODO: 处理点击事件`,
          `    }`,
          `}`,
        ].join("\n"),

        clean: (n) => [
          `// MARK: - Entity`,
          `struct ${n}Entity {`,
          `    let id: String`,
          `    let title: String`,
          `}`,
          ``,
          `// MARK: - Use Case`,
          `protocol ${n}UseCase {`,
          `    func execute() async throws -> [${n}Entity]`,
          `}`,
          ``,
          `class ${n}UseCaseImpl: ${n}UseCase {`,
          `    private let repository: ${n}Repository`,
          ``,
          `    init(repository: ${n}Repository) {`,
          `        self.repository = repository`,
          `    }`,
          ``,
          `    func execute() async throws -> [${n}Entity] {`,
          `        try await repository.fetch${n}()`,
          `    }`,
          `}`,
          ``,
          `// MARK: - Repository`,
          `protocol ${n}Repository {`,
          `    func fetch${n}() async throws -> [${n}Entity]`,
          `}`,
          ``,
          `class ${n}RepositoryImpl: ${n}Repository {`,
          `    func fetch${n}() async throws -> [${n}Entity] {`,
          `        // TODO: 调用网络层或本地存储`,
          `        return []`,
          `    }`,
          `}`,
          ``,
          `// MARK: - Presenter / ViewModel`,
          `@MainActor`,
          `class ${n}Presenter: ObservableObject {`,
          `    @Published var items: [${n}Entity] = []`,
          `    @Published var isLoading = false`,
          ``,
          `    private let useCase: ${n}UseCase`,
          ``,
          `    init(useCase: ${n}UseCase = ${n}UseCaseImpl(repository: ${n}RepositoryImpl())) {`,
          `        self.useCase = useCase`,
          `    }`,
          ``,
          `    func load() async {`,
          `        isLoading = true`,
          `        defer { isLoading = false }`,
          `        items = (try? await useCase.execute()) ?? []`,
          `    }`,
          `}`,
          ``,
          `// MARK: - View`,
          `struct ${n}View: View {`,
          `    @StateObject private var presenter = ${n}Presenter()`,
          ``,
          `    var body: some View {`,
          `        List(presenter.items, id: \.id) { item in`,
          `            Text(item.title)`,
          `        }`,
          `        .navigationTitle("${n}")`,
          `        .task { await presenter.load() }`,
          `    }`,
          `}`,
        ].join("\n"),
      };

      const code = templates[pattern](name);

      return {
        content: [{
          type: "text",
          text: [
            `## ${name} — ${pattern.toUpperCase()} 模板`,
            ``,
            "```swift", 
            code,
            "```",
          ].join("\n"),
        }],
      };
    }
  );
}